### PR TITLE
Homogenize Azure API Management naming

### PR DESCRIPTION
**Pull request by simonkurtz-MSFT**
Update the documentation to reflect the correct product name.

### CODE REVIEW

**Comment by simonkurtz-MSFT** [comment]
@damienaicheh & @reidav, fyi

**Comment by damienaicheh** [comment]
@simonkurtz-MSFT Good idea, it's more consistent!

**Review by ferantoMSFT — APPROVED** [review]

**Comment by simonkurtz-MSFT** [comment]
[like]  Simon Kurtz reacted to your message:
________________________________

**Comment by simonkurtz-MSFT** [comment]
[like]  Simon Kurtz reacted to your message:
________________________________

**Pull request merged**
